name: Test workflow

on:
  push:
    
jobs:
  echo-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test
      
      - name: build
        run: npm run build

      - name: Echo the name
        run: |
          export NAME=Mathias
          echo the $NAME !
  
    deploy:
      runs-on: unbuntu-latest

      needs: build-test

      steps:
        - uses: actions/checkout@v3

        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{secrets.HEROKU_API_kEY}}
            heroku_app_name: "joke-app-iw1"
            heroku-email: "keligbrindeau@gmail.com"